/**
 * Scenario Schemas — Zod contracts for Practice Scenarios generation and grading
 *
 * Single source of truth for LLM structured-output schemas, request validation,
 * and pure sanitizers. Routes and ScenarioService import from here.
 *
 * @author: @gatahcha
 * @date: 2026-07-14
 * @version: 1.0.0
 * @description: Zod schemas and sanitizers for scenario generation and grading.
 */

import { z } from 'zod';
import {
    SCENARIO_BATCH_MAX_COUNT,
    type ScenarioSubQuestionType,
} from '../types/shared';

export const scenarioModeSchema = z.enum(['practice', 'exam']);
export const scenarioSubQuestionIdSchema = z.string().trim().min(1);
export const scenarioGradeSchema = z.number().int().min(1).max(10);
export const scenarioSubQuestionTypeSchema = z.enum([
    'calculation',
    'troubleshoot',
    'action',
    'corrective',
]);

/** Fallback when LLM and instructor override both lack a usable title. */
export const SCENARIO_DEFAULT_TITLE = 'Untitled scenario question';

/** Placeholders for titles that should not be used as the final title. */
const SCENARIO_TITLE_PLACEHOLDERS = new Set(['untitled', SCENARIO_DEFAULT_TITLE.toLowerCase()]);

/**
 * Picks the persisted question title: instructor override wins unless it is a placeholder;
 * otherwise uses the LLM-generated title, then {@link SCENARIO_DEFAULT_TITLE}.
 * 
 * @param instructorTitle - The title provided by the instructor
 * @param generatedTitle - The title generated by the LLM
 * @returns The resolved title
 */
export function resolveScenarioPersistTitle(
    instructorTitle: string | undefined,
    generatedTitle: string
): string {
    const override = instructorTitle?.trim();
    if (override && !SCENARIO_TITLE_PLACEHOLDERS.has(override.toLowerCase())) {
        return override;
    }
    const fromModel = generatedTitle?.trim();
    return fromModel || SCENARIO_DEFAULT_TITLE;
}

/** generatedSubQuestionSchema - LLM generation output: the server assigns subQuestionId during persistence. */
export const generatedSubQuestionSchema = z.object({
    subQuestionType: scenarioSubQuestionTypeSchema,
    prompt: z.string().trim().min(1),
    modelAnswer: z.string().trim().min(1),
});

/**
 * generatedScenarioSchema - Base question returned by the generation LLM.
 */
export const generatedScenarioSchema = z.object({
    title: z.string().trim().min(1).max(120),
    questionBody: z.string().trim().min(1),
    solutionBody: z.string().trim(),
    subQuestions: z.array(generatedSubQuestionSchema).min(1).max(26),
});

/** singleScenarioSchema - One complete generated question — alias used by single-mode structured output. */
export const singleScenarioSchema = generatedScenarioSchema;

export type GeneratedScenario = z.infer<typeof generatedScenarioSchema>;

/** batchScenarioSchema - `batch` mode — an array of independent questions, capped at {@link SCENARIO_BATCH_MAX_COUNT}. */
export const batchScenarioSchema = z.object({
    questions: z.array(generatedScenarioSchema).max(SCENARIO_BATCH_MAX_COUNT),
});

export type GeneratedScenarioBatch = z.infer<typeof batchScenarioSchema>;

/** scenarioPracticeFeedbackResponseSchema - Practice check-answer — TA suggestions only (no grade). */
export const scenarioPracticeFeedbackResponseSchema = z.object({
    feedback: z.string().trim().min(1),
});

export type ScenarioPracticeFeedbackLLMResponse = z.infer<typeof scenarioPracticeFeedbackResponseSchema>;

/** scenarioFeedbackResponseSchema - Exam grading (and legacy single-part grade path). */
export const scenarioFeedbackResponseSchema = z.object({
    grade: scenarioGradeSchema,
    feedback: z.string().trim().min(1),
});

export type ScenarioFeedbackLLMResponse = z.infer<typeof scenarioFeedbackResponseSchema>;

/** Batch exam grading — one LLM structured response for every sub-question answer. */
export const scenarioExamGradingResponseSchema = z.object({
    results: z
        .array(
            z.object({
                subQuestionId: scenarioSubQuestionIdSchema,
                grade: scenarioGradeSchema,
                feedback: z.string().trim().min(1),
            })
        )
        .min(1),
});

/** scenarioExamGradingResponseSchema - Response schema for checking a scenario answer. */
export type ScenarioExamGradingLLMResponse = z.infer<typeof scenarioExamGradingResponseSchema>;

/** checkScenarioAnswerRequestSchema - Request schema for checking a scenario answer. */
export const checkScenarioAnswerRequestSchema = z.object({
    subQuestionId: scenarioSubQuestionIdSchema,
    studentAnswer: z.string().trim().min(1),
    mode: scenarioModeSchema,
});

/** submitScenarioExamRequestSchema - Request schema for submitting a scenario exam answer. */
export const submitScenarioExamRequestSchema = z.object({
    answers: z
        .array(
            z.object({
                subQuestionId: scenarioSubQuestionIdSchema,
                studentAnswer: z.string().trim().min(1),
            })
        )
        .min(1),
});

/** scenarioGenerateRequestSchema - Request schema for generating a scenario. */
export const scenarioGenerateRequestSchema = z.object({
    mode: z.enum(['single', 'batch']),
    sourcePrompt: z.string().trim().min(1),
    topicOrWeekId: z.string().trim().min(1),
    learningObjectiveIds: z.array(z.string().trim().min(1)).optional(),
    subQuestionTypes: z.array(scenarioSubQuestionTypeSchema).min(1).max(26).optional(),
    difficulty: z.enum(['easy', 'medium', 'hard']).optional(),
    title: z.string().trim().optional(),
    count: z.number().int().min(1).max(SCENARIO_BATCH_MAX_COUNT).optional(),
});

/** FALLBACK_FEEDBACK - Fallback feedback for the scenario. */
const FALLBACK_FEEDBACK =
    'Your answer was evaluated against the learning goals for this part. Review the scenario details, check your assumptions and units, and ensure your reasoning addresses the question asked.';

/** FALLBACK_PRACTICE_FEEDBACK - Fallback feedback for the practice scenario. */
const FALLBACK_PRACTICE_FEEDBACK =
    'Thanks for sharing your work. Re-read the scenario details, check your units and assumptions, and see whether your reasoning fully addresses what the question is asking.';

/**
 * sanitizeScenarioPracticeFeedback - Sanitizes the practice feedback
 * 
 * @param raw - The raw practice feedback from the LLM
 * @param modelAnswer - The model answer for the scenario
 * @returns The sanitized practice feedback
 */
export function sanitizeScenarioPracticeFeedback(
    raw: ScenarioPracticeFeedbackLLMResponse,
    modelAnswer: string
): { feedback: string } {
    const feedback = raw.feedback?.trim() || FALLBACK_PRACTICE_FEEDBACK;

    const modelAnswerNormalized = modelAnswer.trim().toLowerCase();
    const leaksModelAnswer =
        modelAnswerNormalized.length > 20 && feedback.toLowerCase().includes(modelAnswerNormalized);

    return {
        feedback: leaksModelAnswer ? FALLBACK_PRACTICE_FEEDBACK : feedback,
    };
}

/**
 * sanitizeScenarioPracticeDescriptiveFeedback - Sanitizes the descriptive practice feedback
 * 
 * @param raw - The raw practice feedback from the LLM
 * @returns The sanitized practice feedback
 */
export function sanitizeScenarioPracticeDescriptiveFeedback(
    raw: ScenarioPracticeFeedbackLLMResponse
): { feedback: string } {
    return {
        feedback: raw.feedback?.trim() || FALLBACK_PRACTICE_FEEDBACK,
    };
}

/** Assembles descriptive-tier feedback with server-attached model answer. */
export function assemblePracticeDescriptiveFeedback(evaluation: string, modelAnswer: string): string {
    const trimmed = evaluation.trim() || FALLBACK_PRACTICE_FEEDBACK;
    const answer = modelAnswer.trim();
    if (!answer) return trimmed;
    return `${trimmed}\n\n---\n**Model answer:**\n${answer}`;
}

/**
 * sanitizeScenarioFeedback - Sanitizes the scenario feedback
 * 
 * Drops model-answer leaks and clamps invalid grades. Always returns a safe
 * `{ grade, feedback }` pair for persistence and API responses.
 * 
 * @param raw - The raw grading response from the LLM
 * @param modelAnswer - The model answer for the scenario
 * @returns The sanitized grading response
 */
export function sanitizeScenarioFeedback(
    raw: ScenarioFeedbackLLMResponse,
    modelAnswer: string
): { grade: number; feedback: string } {
    // Clamp grade to valid 1–10 integer; default to mid-range when LLM returns garbage
    const grade = Number.isInteger(raw.grade) && raw.grade >= 1 && raw.grade <= 10 ? raw.grade : 5;
    const feedback = raw.feedback?.trim() || FALLBACK_FEEDBACK;

    // Reject feedback that quotes the model answer back to the student
    const modelAnswerNormalized = modelAnswer.trim().toLowerCase();
    const leaksModelAnswer =
        modelAnswerNormalized.length > 20 && feedback.toLowerCase().includes(modelAnswerNormalized);

    return {
        grade,
        feedback: leaksModelAnswer ? FALLBACK_FEEDBACK : feedback,
    };
}

/**
 * sanitizeExamGradingResponse - Sanitizes the exam grading response
 * 
 * Validates batch exam grading covers every expected subQuestionId exactly once,
 * sanitizes each grade/feedback pair, and returns results in expectedId order.
 * 
 * @param raw - The raw grading response from the LLM
 * @param expectedSubQuestionIds - The expected subQuestionIds in the order they were asked
 * @param modelAnswersBySubQuestionId - The model answers for each subQuestionId
 * @returns The sanitized grading response
 */
export function sanitizeExamGradingResponse(
    raw: ScenarioExamGradingLLMResponse,
    expectedSubQuestionIds: string[],
    modelAnswersBySubQuestionId: Record<string, string>
): { subQuestionId: string; grade: number; feedback: string }[] | null {
    if (!raw.results?.length) return null;

    // Build map — reject duplicates, unknown ids, or partial coverage
    const byId = new Map<string, { grade: number; feedback: string }>();
    for (const item of raw.results) {
        const id = item.subQuestionId?.trim();
        if (!id || byId.has(id)) return null;
        if (!expectedSubQuestionIds.includes(id)) return null;
        byId.set(id, sanitizeScenarioFeedback(item, modelAnswersBySubQuestionId[id] ?? ''));
    }

    if (byId.size !== expectedSubQuestionIds.length) return null;

    // Return in question order, not LLM result order
    return expectedSubQuestionIds.map((subQuestionId) => {
        const graded = byId.get(subQuestionId)!;
        return { subQuestionId, ...graded };
    });
}

/**
 * sanitizeGeneratedScenario - Sanitizes the generated scenario
 * 
 * Validates generated question has ≥1 complete part; remaps to requested type order when
 * provided. LLM output has no subQuestionId — the server assigns IDs at persist time.
 * 
 * @param raw - The raw generated scenario
 * @param requestedTypes - The requested subQuestionTypes
 * @returns The sanitized generated scenario
 */
export function sanitizeGeneratedScenario(
    raw: GeneratedScenario,
    requestedTypes?: ScenarioSubQuestionType[]
): GeneratedScenario | null {
    // Drop questions with no narrative
    if (!raw.questionBody?.trim()) {
        return null;
    }

    // Keep only complete parts from raw LLM output
    let subQuestions = (raw.subQuestions ?? []).filter(
        (sub) => !!sub.prompt?.trim() && !!sub.modelAnswer?.trim() && !!sub.subQuestionType
    );

    // Remap to instructor-requested type order when types were specified
    if (requestedTypes && requestedTypes.length > 0) {
        subQuestions = requestedTypes
            .map((subQuestionType, index) => {
                const fromModel =
                    raw.subQuestions[index] ??
                    raw.subQuestions.find((s) => s.subQuestionType === subQuestionType) ??
                    raw.subQuestions[0];
                return {
                    subQuestionType,
                    prompt: fromModel?.prompt?.trim() || `Complete the ${subQuestionType} part of this scenario.`,
                    modelAnswer: fromModel?.modelAnswer?.trim() || '',
                };
            })
            .filter((sub) => sub.modelAnswer.length > 0);

        if (subQuestions.length === 0) {
            subQuestions = raw.subQuestions
                .filter((sub) => !!sub.prompt?.trim() && !!sub.modelAnswer?.trim())
                .map((sub, index) => ({
                    subQuestionType: requestedTypes[index] ?? sub.subQuestionType,
                    prompt: sub.prompt.trim(),
                    modelAnswer: sub.modelAnswer.trim(),
                }));
        }
    }

    if (subQuestions.length === 0) {
        return null;
    }

    return {
        title: raw.title?.trim() || SCENARIO_DEFAULT_TITLE,
        questionBody: raw.questionBody.trim(),
        solutionBody: (raw.solutionBody ?? '').trim(),
        subQuestions,
    };
}
