/**
 * guardrail-schema.ts
 *
 * Zod schema and post-processing for Guided Pathways guardrail evaluation (P0).
 * LLM returns one guardrailType; server maps to static templates (none = proceed to main chat).
 */

import { z } from 'zod';
import {
    ACTIVE_GUARDRAILS_P0,
    formatGuardrailResponseTemplate,
    type GuardrailDefinition,
    type GuardrailId,
} from './guided-pathways-modules';

/** All values the evaluator LLM may return, including none when no guardrail applies. */
export const GUARDRAIL_TYPE_ENUM = z.enum([
    'mental-health-crisis',
    'inappropriate-content',
    'off-topic',
    'none',
]);

/**
 * Zod schema passed to `LLMModule.sendStructuredConversation` for guardrail evaluation.
 * Student-facing copy is not generated by the model in P0.
 */
export const guardrailEvaluationResponseSchema = z.object({
    guardrailType: GUARDRAIL_TYPE_ENUM,
});

/** Parsed shape of {@link guardrailEvaluationResponseSchema}. */
export type GuardrailEvaluationResponse = z.infer<typeof guardrailEvaluationResponseSchema>;

/** LLM guardrail classification including none. */
export type GuardrailType = z.infer<typeof GUARDRAIL_TYPE_ENUM>;

/** Result returned to chat-app after evaluation and server-side resolution. */
export interface GuardrailResult {
    triggered: boolean;
    winningGuardrailId: GuardrailId | null;
    responseText: string | null;
}

const NO_TRIGGER_RESULT: GuardrailResult = {
    triggered: false,
    winningGuardrailId: null,
    responseText: null,
};

/**
 * Build the final guardrail result from the LLM guardrailType and course context.
 *
 * @param guardrailType - Evaluator output (`none` when message is on-topic and appropriate).
 * @param courseName - Course display name for template substitution.
 * @param guardrails - Active guardrail definitions.
 * @returns {@link GuardrailResult} for the chat pipeline.
 */
export function buildGuardrailResult(
    guardrailType: GuardrailType,
    courseName: string,
    guardrails: readonly GuardrailDefinition[] = ACTIVE_GUARDRAILS_P0
): GuardrailResult {
    if (guardrailType === 'none') {
        return { ...NO_TRIGGER_RESULT };
    }

    const definition = guardrails.find((g) => g.id === guardrailType);
    if (!definition) {
        return { ...NO_TRIGGER_RESULT };
    }

    return {
        triggered: true,
        winningGuardrailId: guardrailType,
        responseText: formatGuardrailResponseTemplate(definition.responseTemplate, courseName),
    };
}

/** Fail-open result when evaluation cannot complete. */
export function noGuardrailTriggerResult(): GuardrailResult {
    return { ...NO_TRIGGER_RESULT };
}
