/**
 * Build-time git commit info, generated by scripts/generate-build-info.cjs and
 * copied into dist/generated/build-info.json as part of `npm run build`.
 * Read via fs (not a static import) so a missing file - e.g. before the first
 * build, or in tests, which never run the generator - falls back cleanly
 * instead of failing to compile/resolve.
 */

import fs from 'fs';
import path from 'path';
import { Response } from 'express';
import { appVersion } from './app-version';

export interface BuildInfo {
    commit: string;
    commitShort: string;
}

const FALLBACK: BuildInfo = {
    commit: 'unknown',
    commitShort: 'unknown'
};

function loadBuildInfo(): BuildInfo {
    try {
        const filePath = path.join(__dirname, '../generated/build-info.json');
        const raw = fs.readFileSync(filePath, 'utf-8');
        return { ...FALLBACK, ...JSON.parse(raw) };
    } catch {
        return FALLBACK;
    }
}

export const buildInfo: BuildInfo = loadBuildInfo();

const buildComment = `<!-- build: v${appVersion} | commit: ${buildInfo.commitShort} (${buildInfo.commit}) -->`;

/**
 * Reads the HTML file at filePath, inserts the build comment after `<!DOCTYPE html>`
 * so it's visible via "View Source", and sends it. Use in place of `res.sendFile(filePath)`
 * for page shells.
 */
export function sendHtmlPageWithBuildComment(res: Response, filePath: string, status = 200): void {
    const html = fs.readFileSync(filePath, 'utf-8');
    const withComment = html.replace(/<!DOCTYPE html>/i, `<!DOCTYPE html>\n${buildComment}`);
    res.status(status).type('html').send(withComment);
}
